checkpoint_dir: "/storage/matt_models/inpainting/"
data_path: "/storage/FFHQ/ffhq256"
data_path_test: "/storage/FFHQ/ffhq256_900_if"
batch_size: 1
image_size: 256

conditioning:
  method: ps
  params:
    scale: 1.8

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 61
    intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.0
