checkpoint_dir: "/storage/matt_models/inpainting/"
data_path: "/storage/FFHQ/ffhq256"
data_path_test: "/storage/FFHQ/ffhq256_900_if"
batch_size: 1
image_size: 256

conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.0
